---
file: admin/config/status.yaml
title: 상태 enum 및 표시 규칙
owner: duksan
created: 2025-09-22 08:00 UTC / 2025-09-22 17:00 KST
updated: 2025-09-23 07:37 UTC / 2025-09-23 16:37 KST
status: active
tags: [config, status]
schemaVersion: 1
description: 표준 상태 집합과 색상/아이콘 매핑
---
enum:
  in_progress:
    label: 진행중
    color: '#1d4ed8' # blue-700
    icon: play
  pending:
    label: 대기
    color: '#6b7280' # gray-500
    icon: pause
  on_hold:
    label: 보류
    color: '#a855f7' # purple-500
    icon: stop
  failed:
    label: 실패
    color: '#ef4444' # red-500
    icon: x
  design_change:
    label: 설계변경중
    color: '#f59e0b' # amber-500
    icon: refresh
  completed:
    label: 완료
    color: '#15803d' # green-700
    icon: check
