/**
 * file: apps/web/src/app/layout.tsx
 * owner: duksan
 * created: 2025-09-23 16:10 UTC / 2025-09-24 01:10 KST
 * updated: 2025-09-23 17:28 UTC / 2025-09-24 02:28 KST
 * purpose: Next.js App Router 루트 레이아웃. 전역 다크 모드 고정 및 전역 스타일 주입.
 * doc_refs: ["apps/web/README.md", "basesettings.md", "admin/plan/m1-kickoff.md"]
 */

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '../styles/fullcalendar.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="dark" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
