name: Auto Enable PR Auto-Merge

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  enable-automerge:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            try {
              const query = `mutation($pr:ID!, $method: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(input:{pullRequestId:$pr, mergeMethod:$method}) {
                  clientMutationId
                }
              }`
              await github.graphql(query, { pr: pr.node_id, method: 'SQUASH' })
              core.info('Auto-merge enabled (SQUASH)')
            } catch (e) {
              core.warning('Auto-merge enable failed: ' + e.message)
            }
