name: Docs Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install markdownlint-cli
        run: npm i -g markdownlint-cli@0.38.0

      - name: Install ajv-cli and js-yaml
        run: npm i -g ajv-cli@5.0.0 js-yaml@4.1.0

      - name: Run markdownlint (MD029 ordered)
        run: markdownlint -q -c .markdownlint.json "**/*.md"

      - name: Run local docs validator
        run: bash scripts/validate_docs.sh

      - name: Validate hub manifests against schema
        if: ${{ always() }}
        run: |
          set -e
          shopt -s nullglob
          for f in admin/manifests/*.yaml; do
            echo "Validating $f"
            tmp="$(mktemp).json"
            js-yaml "$f" > "$tmp"
            ajv validate -s admin/schemas/hub.schema.json -d "$tmp"
            rm -f "$tmp"
          done
